version: "3"

networks:
  documentable-net:

volumes:
  documentable-db:
  documentable-vue-app:


services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    networks:
      - documentable-net
    restart: on-failure
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
    ports:
      - "9411:9411"
      - "16686:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14268:14268"
      - "14250:14250"

  documentable-db:
    container_name: documentable-db
    restart: always
    image: documentable-db
    build:
      context: ./db
    volumes:
      - documentable-db:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - documentable-net
    ports:
      - 5435:5432

  documentable-graphql:
    container_name: documentable-graphql
    restart: always
    image: documentable-graphql
    build:
      context: ./graphql
    env_file:
      - ./.env
    depends_on:
      - documentable-db
    networks:
      - documentable-net
    ports:
      - 5433:5433
    command: ["--connection", "${DATABASE_URL}", "--port", "5433", "--schema", "app_public", "--default-role", "app_anonymous", "--jwt-secret", "${JWT_SECRET}", "--jwt-token-identifier", "app_public.jwt_token", "--enhance-graphiql", "--append-plugins", "postgraphile-plugin-connection-filter,tracing-plugin"]

  documentable-vue-app:
    container_name: documentable-vue-app
    restart: always
    build:
      context: ./vue-app
      dockerfile: Dockerfile
    volumes:
      - 'documentable-vue-app:/app'
      - '/app/node_modules'
    depends_on:
      - documentable-graphql
    networks:
      - documentable-net
    ports:
      - 8080:8080
